Update faq with LSF build dependencies.
open-mpi/ompi-www pull request #403
Opened 2021-12-17 19:21 UTC by awlauria

Some of these may be dated and could be removed.

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

2021-12-21 14:47 UTC, jjhursey approved these changes

2021-12-30 22:25 UTC, jsquyres requested changes

2021-12-30 22:25 UTC, jsquyres commented on faq/building.inc
> +   - On IRIX < 6: it should be in libsun (IRIX 6 and later it is in libc).
Open MPI hasn't supported AIX, HP-UX, or IRIX for many years.  It's probably not worth listing them.

2022-01-10 19:30 UTC, awlauria commented
@jsquyres thanks, updated

2022-01-10 19:45 UTC, jsquyres approved these changes

2022-01-10 19:56 UTC, merged